feat: Upgrade Terraform to 1.2.8
cds-snc/dns pull request #262
Opened 2022-08-30 18:32 UTC by gcharest

# Summary | Résumé

Upgrade Terraform from 0.13.6 to 1.2.8

Fix #254 

# Test instructions | Instructions pour tester la modification

2022-08-30 18:43 UTC, CalvinRodo requested changes
Terraform has an upgrade guide to 1.x. While this looks like it works it's probably better to follow the guide. 

https://www.terraform.io/language/upgrade-guides/1-0

2022-08-31 14:06 UTC, patheard approved these changes

2022-08-31 14:23 UTC, gcharest commented
According to the guide, we need to move from 0.13.8 --> 0.14.0 --> 1.0.0 --> 1.1.0 --> 1.2.0:

So this PR is now to move to 0.14.0 as a step towards the final version.

2022-08-31 14:32 UTC, CalvinRodo approved these changes

2022-08-31 14:32 UTC, merged