Adding a new iam role that will allow notify to manage notifcation.canada.ca domain
cds-snc/dns pull request #397
Opened 2024-07-10 19:23 UTC by sylviamclaughlin

# Summary | Résumé

New IAM role that will allow the following:
1. List hosted zones, get hosted zones count and list hosted zone names permissions.
2. Change hosted zone records only for notification.canada.ca hosted zone.
3. Allow this role to be assumed by the github oidc role

2024-07-10 19:27 UTC, gcharest approved these changes
LGTM! Thanks for handling this!

2024-07-11 12:05 UTC, ben851 commented
This looks good, but we will also need the notify core team to have at least read access to the zone so that we can do debugging etc.

2024-07-11 13:36 UTC, gcharest requested changes
Before committing, let's sync with @ben851 to confirm the required permissions

2024-07-11 17:34 UTC, gcharest approved these changes

2024-07-11 17:34 UTC, merged